"""sync push dispatcher

Revision ID: f5c09c0f7f18
Revises: e4b05c0f299b
Create Date: 2026-07-24 02:04:18.762584

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "f5c09c0f7f18"
down_revision: str | Sequence[str] | None = "e4b05c0f299b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Idempotency key for pushed offline mutations.
    op.add_column(
        "change_log",
        sa.Column("client_mutation_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_unique_constraint(
        "uq_change_log_client_mutation_id", "change_log", ["client_mutation_id"]
    )

    # server_seq was scaffolded as a plain BigInteger with no sequence, so it
    # was never actually auto-populated (the append path was a stub until the
    # dispatcher landed). Promote it to a real IDENTITY column. The table is
    # empty in practice, so ADD GENERATED is safe.
    op.execute("ALTER TABLE change_log ALTER COLUMN server_seq DROP DEFAULT")
    op.execute(
        "ALTER TABLE change_log ALTER COLUMN server_seq ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE change_log ALTER COLUMN server_seq DROP IDENTITY IF EXISTS")
    op.drop_constraint("uq_change_log_client_mutation_id", "change_log", type_="unique")
    op.drop_column("change_log", "client_mutation_id")
